export const ActionTypes = {
  CREATE_BLOG : 'CREATE_BLOG',
  INITIAL_BLOGS : 'INITIAL_BLOGS',
  REMOVE_BLOG : 'REMOVE_BLOG',
  LIKE_BLOG: 'LIKE_BLOG',
  SET_NOTIFICATION : 'SET_NOTIFICATION',
  REMOVE_NOTIFICATION : 'REMOVE_NOTIFICATION'
}